POST http://localhost:5000/api/v1/auth/signup
Content-Type: application/json

{
    "name":"John Smith",
    "email":"a2.business@gmail.com",
    "password":"password123",
    "confirm_password":"password123"
}

###
POST http://localhost:5000/api/v1/auth/signin
Content-Type: application/json

{
    "email":"phelanwhite.business@gmail.com",
    "password":"password123"
}

###
DELETE  http://localhost:5000/api/v1/auth/signout

###
POST http://localhost:5000/api/v1/auth/refresh-token

###
PUT http://localhost:5000/api/v1/auth/change-password
Content-Type: application/json
Authorization: 

{
    "new_password":"password123",
    "confirm_new_password":"password123"
}

###
GET  http://localhost:5000/api/v1/auth/get-me

###
PUT http://localhost:5000/api/v1/auth/update-me
Content-Type: application/json


{
    "name":"phelanwhite.business@gmail.com"
}

###
PUT http://localhost:5000/api/v1/auth/forgot-password
Content-Type: application/json

{
    "email":"phelanwhite.business@gmail.com"
}

###
PUT http://localhost:5000/api/v1/auth/reset-password/6497087f2e4d5c1be627d41b20350e244665ea1829b292c94bd132ee4dbd413d
Content-Type: application/json

{
    "new_password":"password123",
    "confirm_new_password":"password123"
}